repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
  - hooks:
      - id: fmt
        stages:
          - commit
      - id: cargo-check
        stages:
          - commit
    repo: https://github.com/doublify/pre-commit-rust
    rev: master